### ISSUE TITLE
Create DOI on Zenodo

### ISSUE THREAD

**Issue by kequach** [MarcelRobeer/ContrastiveExplanation#12]
I wanted to ask if you considered to create a DOI for the Contrastive Explanation. This allows researchers to reference a version of the package with ease and can be done with Zenodo for example. There is also great integration between Zenodo, which creates a new DOI and a persistent copy of the repository for each release, and Github. You can find instructions on how to create a DOI here from official Github docs: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content 
This step helps with visibility of this repository and therefore making your research software more used.

On a similar note, it also helps researchers to know how to correctly cite the software. I see that you already added this in the readme but Github also offers the citation file format which also shows up on the top right if used: 
![image](https://user-images.githubusercontent.com/18238845/156461771-0887b9dd-4ff0-4335-8fbd-342f4fee08a1.png)
You can find more information about it here: https://citation-file-format.github.io/ 

I would be happy to help with this if you have any questions.

**Comment by MarcelRobeer** [comment]
Thanks for the tip, added a CITATION.cff file
