### ISSUE TITLE
TypeError in the example notebook

### ISSUE THREAD

**Issue by Naviden** [MarcelRobeer/ContrastiveExplanation#5]
running the example notebook (Contrastive explanation - example usage), the line `exp.explain_instance_domain(model.predict_proba, sample)`
gives the following error:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/16959102/86345387-c1f00580-bc5b-11ea-88e7-44c6783e5a4a.png">

**Comment by MarcelRobeer** [comment]
Hi Naviden,

I am unable to reproduce this error. Can you provide me with your package versions for _LIME_, _scikit-learn_ and _numpy_?

**Comment by Naviden** [comment]
Hi Marcel,
Here are the versions:

Python: 3.7.4
lime==0.2.0.0
scikit-learn==0.22.2.post1
numpy==1.18.4

thanks :)

**Comment by MarcelRobeer** [comment]
Commit 86f8d53 should fix this bug. I dropped the dependency on LIME.
