### ISSUE TITLE
Changing output every run

### ISSUE THREAD

**Issue by Subh1m** [MarcelRobeer/ContrastiveExplanation#9]
Hi,

When I run the `exp.explain_instance_domain(model.predict_proba, sample)` , I get different output everytime.
After every run, a different column is given as output.

Is there a way I can get constant results?

**Comment by MarcelRobeer** [comment]
All steps in the process should be seeded by a (numpy) seed, and therefore obtain the same results when re-running. Sometimes predictive models are stochastic (have slightly different outputs each time), but I am unable to determine that for your case in particular. Do you have a minimal working example so I can reproduce this error?

**Comment by arsine1996** [comment]
I have the same issue, different results when rerunning, even with the specified seed. But, after some iterations the suggestions start to repeat themselves. Is that some logic behind that it first returns the best output?

**Comment by Subh1m** [comment]
I found the solution. Just change the parameter generate_data to `generate_data=False`. You start getting same output for single row. The reason being it will now only look into the training set and not generate neighborhood data.

**Comment by arsine1996** [comment]
thank you, it worked.

**Comment by Subh1m** [comment]
My pleasure.
